### ISSUE TITLE
`cabal-fmt: expand` does not work

### ISSUE THREAD

**Issue by coclique** [berberman/vscode-cabal-fmt#2]
`cabal-fmt` supports [auto-expanding `exposed-modules`](http://oleg.fi/gists/posts/2019-08-11-cabal-fmt.html#extra-expand-exposed-modules-and-other-modules), however by creating temporary files for formatting, `cabal-fmt` is unable to find the correct directory and gives errors like:

```
cabal-fmt: /tmp/src: getDirectoryContents:openDirStream: does not exist (No such file or directory)
```

**Comment by berberman** [comment]
Thanks for the issue. It seems that `cabal-fmt` always takes the directory of input cabal file as root dir to find modules (https://github.com/phadej/cabal-fmt/blob/6651ffdccdfce71330f2b5cde9f8f23b616abf82/cli/Main.hs?_pjax=%23js-repo-pjax-container%2C%20div%5Bitemtype%3D%22http%3A%2F%2Fschema.org%2FSoftwareSourceCode%22%5D%20main%2C%20%5Bdata-pjax-container%5D#L58). In order to make it work, I think we will have to create the temp file of current buffer content in project root, instead of in tempdir as now.
